name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.BUILDBOT_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Backlog
    steps:
      - name: Assign NEW issues to Backlog project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: "https://github.com/orgs/beer-garden/projects/24"
          column_name: "New Issues"
