name: Auto Assign to Project

on:
  issues:
    types:
      - opened

jobs:
  assign_project:
    runs-on: ubuntu-latest
    name: Assign Project
    steps:
      - uses: actions/add-to-project@v0.4.0
        name: Assign new issues to Dev project
        with:
          project-url: https://github.com/orgs/beer-garden/projects/27
          github-token: ${{ secrets.FUNCTIONARY_BUILDBOT_TOKEN }}
