name: Auto Assign to Project

on:
  issues:
    types: [opened]

jobs:
  assign_project:
    runs-on: ubuntu-latest
    name: Assign Project
    steps:
      - name: Assign NEW issues to Dev project
        uses: KekeHub/auto-assign-project@v1
        with:
          token: ${{ secrets.BUILDBOT_TOKEN }}
          owner: beer-garden
          project-id: 27
